/*
Copyright (c) 2009-2016 Roger Light <roger@atchoo.org>

All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
and Eclipse Distribution License v1.0 which accompany this distribution.
 
The Eclipse Public License is available at
   http://www.eclipse.org/legal/epl-v10.html
and the Eclipse Distribution License is available at
  http://www.eclipse.org/org/documents/edl-v10.php.
 
Contributors:
   Roger Light - initial implementation and documentation.
*/

#ifndef MQTT3_PROTOCOL_H
#define MQTT3_PROTOCOL_H

/* For version 3 of the MQTT protocol */

#define PROTOCOL_NAME_v31 "MQIsdp"
#define PROTOCOL_VERSION_v31 3

#define PROTOCOL_NAME_v311 "MQTT"
#define PROTOCOL_VERSION_v311 4

#define PROTOCOL_NAME_v5 "MQTT"
#define PROTOCOL_VERSION_v5 5


/* Message types */
#define CONNECT 0x10
#define CONNACK 0x20
#define PUBLISH 0x30
#define PUBACK 0x40
#define PUBREC 0x50
#define PUBREL 0x60
#define PUBCOMP 0x70
#define SUBSCRIBE 0x80
#define SUBACK 0x90
#define UNSUBSCRIBE 0xA0
#define UNSUBACK 0xB0
#define PINGREQ 0xC0
#define PINGRESP 0xD0
#define DISCONNECT 0xE0
#define AUTH 0xF9

enum mqtt311_connack_codes {
	CONNACK_ACCEPTED = 0,
	CONNACK_REFUSED_PROTOCOL_VERSION = 1,
	CONNACK_REFUSED_IDENTIFIER_REJECTED = 2,
	CONNACK_REFUSED_SERVER_UNAVAILABLE = 3,
	CONNACK_REFUSED_BAD_USERNAME_PASSWORD = 4,
	CONNACK_REFUSED_NOT_AUTHORIZED = 5,
};


enum mqtt5_return_codes {
	RC5_NORMAL = 0, /* DISCONNECT */
	RC5_SUCCESS = 0, /* UNSUBSCRIBE, AUTHENTICATE */
	RC5_QOS0 = 0, /* SUBSCRIBE */
	RC5_QOS1 = 1, /* SUBSCRIBE */
	RC5_QOS2 = 2, /* SUBSCRIBE */
	RC5_NO_MATCHING_SUBSCRIBERS = 16, /* PUBREC, PUBACK */
	RC5_NO_SUBSCRIPTION_EXISTED = 17, /* UNSUBSCRIBE */
	RC5_CONTINUE = 34, /* AUTHENTICATE */
	RC5_REAUTHENTICATE = 35, /* AUTHENTICATE */

	RC5_UNSPECIFIED = 128, /* CONNECT, PUBACK, PUBREC, SUBSCRIBE, UNSUBSCRIBE, DISCONNECT */
	RC5_MALFORMED_CONTROL_PACKET = 129, /* CONNECT, DISCONNECT */
	RC5_PROTOCOL_ERROR = 130, /* DISCONNECT */
	RC5_IMPLEMENTATION_SPECIFIC = 131, /* CONNECT, PUBACK, PUBREC, SUBSCRIBE, UNSUBSCRIBE, DISCONNECT */
	RC5_UNSUPPORTED_PROTOCOL_VERSION = 132, /* CONNECT */
	RC5_CLIENTID_NOT_VALID = 133, /* CONNECT */
	RC5_BAD_USERNAME_OR_PASSWORD = 134, /* CONNECT */
	RC5_NOT_AUTHORIZED = 135, /* CONNECT, PUBACK, PUBREC, SUBSCRIBE, UNSUBSCRIBE, DISCONNECT */
	RC5_SERVER_UNAVAILABLE = 136, /* CONNECT */
	RC5_SERVER_BUSY = 137, /* CONNECT, DISCONNECT */
	RC5_BANNED = 138, /* CONNECT */
	RC5_DISCONNECT_SERVER_SHUTTING_DOWN = 139,
	RC5_CONNECT_BAD_AUTHENTICATION_METHOD = 140,
	RC5_DISCONNECT_SESSION_TAKEN_OVER = 142,
	RC5_DISCONNECT_KEEP_ALIVE_TIMEOUT = 143,
	RC5_TOPIC_INVALID = 144, /* CONNECT, PUBACK, PUBREC, SUBSCRIBE, UNSUBSCRIBE, DISCONNECT */
	RC5_PACKET_ID_IN_USE = 145, /* SUBSCRIBE, UNSUBSCRIBE */
	RC5_PACKET_ID_NOT_FOUND = 146, /* PUBREL, PUBCOMP */
	RC5_PACKET_TOO_LARGE = 149, /* CONNECT, PUBACK, PUBREC, DISCONNECT */
	RC5_MESSAGE_RATE_TOO_HIGH = 150, /* DISCONNECT */
	RC5_QUOTA_EXCEEDED = 151, /* PUBACK, PUBREC, SUBSCRIBE, DISCONNECT */
	RC5_ADMINISTRATIVE_ACTION = 152, /* DISCONNECT */
	RC5_WITH_WILL = 153, /* DISCONNECT */
	RC5_DISCONNECT_ALIAS_NOT_ACCEPTED = 154,
	RC5_PUBREC_QOS_LEVEL_NOT_SUPPORTED = 154,
	RC5_PUBACK_QOS_LEVEL_NOT_SUPPORTED = 154,
	RC5_NO_TOPIC = 155, /* DISCONNECT */
	RC5_USE_ANOTHER_SERVER = 156, /* CONNECT, DISCONNECT */
	RC5_SERVER_MOVED = 157, /* CONNECT, DISCONNECT */
	RC5_SHARED_SUBSCRIPTION_NOT_SUPPORTED = 158, /* SUBSCRIBE */
	RC5_SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTS = 159, /* SUBSCRIBE */
	RC5_CONNECT_CONNECTION_RATE_EXCEEDED = 159,
	RC5_MAXIMUM_CONNECTION_TIME = 160, /* DISCONNECT */
};

#define MQTT_MAX_PAYLOAD 268435455

#endif
